<?php

require_once(SITE_ROOT . '/models/BaseModel.php');

class NoteModel extends BaseModel
{
protected $table = 'notes';
    protected $joins = ['contacts' => "`notes`.`foreign_id` = :id1 AND `notes`.`parent` = 'contacts'"];


    public function prepAndSave($data)
    {
        parent::prepAndSave($data); // TODO: Change the autogenerated stub

        if ($this->hasNote($data) && $this->hasIdAndParent($data)){
            $data['note']['created'] = date('Y-m-d H:i:s');
            return $this->save($data['note']);
        }
        return null;
    }

    protected function hasNote($data){
        return (!empty($data['note']['note']) );
    }
    protected function hasIdAndParent($data){
        $hasId = (array_key_exists('foreign_id', $data['notes']['foreign_id']) && !empty($data['notes']['foreign_id']));
        $hasParent = (array_key_exists('foreign_id', $data['notes']['parent']) && !empty($data['notes']['parent']));
        return ($hasId && $hasParent);
    }
}